<?php
namespace common\extensions\external_repository_manager\implementation\alfresco;

use common\extensions\external_repository_manager\DefaultExternalRepositoryObjectTableDataProvider;

class AlfrescoExternalRepositoryTableDataProvider extends DefaultExternalRepositoryObjectTableDataProvider
{
}
?>